# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ZCY-CW\Documents\GitHub\AutoGenerateProject\generater\gui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        Dialog.resize(251, 267)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("generater/gui/icons/main_icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setToolTip("")
        Dialog.setAccessibleName("")
        Dialog.setAutoFillBackground(True)
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 1, 1, 4)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 4)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 4)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.HLine)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 6, 0, 1, 5)
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 4)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 3, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 4, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 7, 2, 1, 1)
        self.setFixedSize(self.width(), self.height())
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Auto-G"))
        self.label_5.setText(_translate("Dialog", "业务类型："))
        self.label.setText(_translate("Dialog", "凭证日期："))
        self.label_3.setText(_translate("Dialog", "制单人："))
        self.label_4.setText(_translate("Dialog", "通道名称："))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "物联网业务必填"))
        self.comboBox.setItemText(1, _translate("Dialog", "收入"))
        self.comboBox.setItemText(2, _translate("Dialog", "成本"))
        self.comboBox.setItemText(3, _translate("Dialog", "收款"))
        self.comboBox.setItemText(4, _translate("Dialog", "付款"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "流量"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "语音"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "物联网"))
        self.pushButton_2.setText(_translate("Dialog", "退出"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "黎光波"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "王静"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "张哲"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "林嘉铭"))
        self.label_2.setText(_translate("Dialog", "凭证类型："))
        self.pushButton.setText(_translate("Dialog", "生成凭证"))
